apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n46ewq2ku-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n46ewq2ku-java-quarkus-gitops